// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs3i1QbrK6jvYo84-8OxouTJpDB7ksZX8',
    appId: '1:607942899331:web:18eed102700dc8d3fb4db6',
    messagingSenderId: '607942899331',
    projectId: 'banco-mobile-4d123',
    authDomain: 'banco-mobile-4d123.firebaseapp.com',
    storageBucket: 'banco-mobile-4d123.firebasestorage.app',
    measurementId: 'G-W9DKNKPFBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClFYUqBxH09dUtkpUBjP1EWcKmc0AImrI',
    appId: '1:607942899331:android:1d02ea3ff5ed1590fb4db6',
    messagingSenderId: '607942899331',
    projectId: 'banco-mobile-4d123',
    storageBucket: 'banco-mobile-4d123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCroe1W5oBemxcaubWspTxO0LkKCdaeDk4',
    appId: '1:607942899331:ios:c10f9e335a6fdbf7fb4db6',
    messagingSenderId: '607942899331',
    projectId: 'banco-mobile-4d123',
    storageBucket: 'banco-mobile-4d123.firebasestorage.app',
    iosBundleId: 'com.example.bancoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCroe1W5oBemxcaubWspTxO0LkKCdaeDk4',
    appId: '1:607942899331:ios:c10f9e335a6fdbf7fb4db6',
    messagingSenderId: '607942899331',
    projectId: 'banco-mobile-4d123',
    storageBucket: 'banco-mobile-4d123.firebasestorage.app',
    iosBundleId: 'com.example.bancoMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs3i1QbrK6jvYo84-8OxouTJpDB7ksZX8',
    appId: '1:607942899331:web:c8b1f9cb1297079afb4db6',
    messagingSenderId: '607942899331',
    projectId: 'banco-mobile-4d123',
    authDomain: 'banco-mobile-4d123.firebaseapp.com',
    storageBucket: 'banco-mobile-4d123.firebasestorage.app',
    measurementId: 'G-62NMJMSVV2',
  );
}
